export const demoData = [
  {
    id: 1,
    title: "Apple iPhone 14 Pro Max price in Bangladesh",
    img: "https://dnc8pt3q0ulny.cloudfront.net/rp/media/14pmp1.jpg",
    Display: "6.7″ LTPO Super Retina XDR OLED (1290x2796 px)",
    Camera: "Back: 48+12+12+TOF 3D & Front: 12+SL 3D",
    OS: "iOS 16",
    RAM: "6 GB",
    ROM: "1TB",
    Battery: "Li-Ion 4323 mAh",
    price: "৳201,599.00",
    description:
      "With this intention, All of our product data collection sources are on the Internet. Our team shared all kinds of reviews, details, and prices in Bangladesh that have been collected from various websites on the Internet. We have tried to present the information to you through verification and selection from the internet. We sincerely apologize for any inconvenience this may cause. Before buying any product, you should check and choose well.",
  },
  {
    id: 2,
    title: "Apple iPhone 14",
    img: "https://www.mobiledokan.co/wp-content/uploads/2021/09/Apple-iPhone-14-Midnight.jpg",
    OS: "iOS 16",
    Display: "6.1 1170x2532 pixels",
    Camera: "12MP 2160p",
    RAM: "6GB ",
    ROM: "512 GB",
    Battery: "3279mAh Li-Ion",
    price: "৳146,999.00",
    description:
      "Apple iPhone 14 will be launched in September 2022. The iPhone 14 launched with the model numbers A2882, A2649, A2881, A2884, A2883, and iPhone 15,5. Firstly, Its dimensional measure is 146.7 x 71.5 x 7.7 mm and the weight is 172 grams. Secondly, the display of the iPhone 14 is a 6.1-inch Super Retina XDR OLED panel with 1170 x 2532 pixels resolution. The display is protected from Scratch-resistant ceramic glass and oleophobic coating. Thirdly and most importantly, It is powered by Apple A16 Bionic and running with iOS 15. Moreover, it has a Hexa-core (23.23 GHz Avalanche + 41.82 GHz Blizzard) CPU.",
  },
  {
    id: 3,
    title: "Apple iPhone 13 Pro Max Full Specifications",
    img: "https://www.mobiledokan.com/wp-content/uploads/2021/10/Apple-iPhone-13-Pro-Max-image.jpg",
    Display: "	6.7 inches 1284 x 2778 pixels (458 ppi)",
    Camera: "Back: 12+12 & Front: 12+SL 3D",
    OS: "iOS 15",
    RAM: "6 GB",
    ROM: "512 GB",
    Battery: "Lithium-ion 4352 mAh (non-removable)",
    price: "৳176,999 ",
    description:
      "Apple iPhone 13 Pro Max comes with a 6.7 inches Super Retina XDR OLED Full HD+ screen. It has a Apple iPhone notch design. The back camera is of quad 12+12+12 Megapixel + TOF 3D LiDAR scanner with powerful image processing capability and 4K video recording. The front one is of Dual 12 MP and SL 3D camera. Apple iPhone 13 Pro Max comes with 4352 mAh battery with 27W fast charging solution. It has 6 GB RAM, up to 3.22 GHz Hexa-core CPU and Apple GPU. It is powered by a 5 nm Apple A15 Bionic chipset. The device comes with 128, 256, 512 GB or 1 TB internal storage.",
  },
  {
    id: 4,
    title: "Apple iPhone 13 price in Bangladesh",
    img: "https://www.bdprice.com.bd/wp-content/uploads/2020/11/Apple-iPhone-13-Blue-Price-in-Bangladesh.jpg",
    Display: "6.1″ Super Retina XDR OLED (1170x2532 px)",
    Camera: "Back: 12+12 & Front: 12+SL 3D",
    OS: "iOS 15",
    RAM: "4 GB",
    ROM: "512 GB",
    Battery: "Li-Ion 3240 mAh",
    price: "৳118000",
    description:
      "2x optical zoom out, Digital zoom up to 5x, Portrait mode with advanced bokeh and Depth Control, Portrait Lighting with six effects (Natural, Studio, Contour, Stage, Stage Mono, HighKey Mono), Sensorshift optical image stabilization (Wide), Sevenelement lens (Wide), fiveelement lens (Ultra Wide), True Tone flash with Slow Sync, Panorama (up to 63MP), Sapphire crystal lens cover, 100% Focus Pixels (Wide), Night mode, Deep Fusion, Smart HDR 4, Photographic Styles, Wide color capture for photos and Live Photos, Lens correction (Ultra Wide), Advanced redeye correction, Auto image stabilization, Burst mode, Photo geotagging, Image formats captured: HEIF and JPEG, Audio zoom, True Tone flash, QuickTake video, Timelapse video with stabilization, Night mode Time-lapse, Stereo recording, Playback zoom",
  },
  {
    id: 5,
    title: "Apple iPhone 14 Pro Max price in Bangladesh",
    img: "https://dnc8pt3q0ulny.cloudfront.net/rp/media/14pmp1.jpg",
    Display: "6.7″ LTPO Super Retina XDR OLED (1290x2796 px)",
    Camera: "Back: 48+12+12+TOF 3D & Front: 12+SL 3D",
    OS: "iOS 16",
    RAM: "6 GB",
    ROM: "1TB",
    Battery: "Li-Ion 4323 mAh",
    price: "৳201,599.00",
    description:
      "With this intention, All of our product data collection sources are on the Internet. Our team shared all kinds of reviews, details, and prices in Bangladesh that have been collected from various websites on the Internet. We have tried to present the information to you through verification and selection from the internet. We sincerely apologize for any inconvenience this may cause. Before buying any product, you should check and choose well.",
  },
  {
    id: 6,
    title: "Apple iPhone 14",
    img: "https://www.mobiledokan.co/wp-content/uploads/2021/09/Apple-iPhone-14-Midnight.jpg",
    OS: "iOS 16",
    Display: "6.1 1170x2532 pixels",
    Camera: "12MP 2160p",
    RAM: "6GB ",
    ROM: "512 GB",
    Battery: "3279mAh Li-Ion",
    price: "৳146,999.00",
    description:
      "Apple iPhone 14 will be launched in September 2022. The iPhone 14 launched with the model numbers A2882, A2649, A2881, A2884, A2883, and iPhone 15,5. Firstly, Its dimensional measure is 146.7 x 71.5 x 7.7 mm and the weight is 172 grams. Secondly, the display of the iPhone 14 is a 6.1-inch Super Retina XDR OLED panel with 1170 x 2532 pixels resolution. The display is protected from Scratch-resistant ceramic glass and oleophobic coating. Thirdly and most importantly, It is powered by Apple A16 Bionic and running with iOS 15. Moreover, it has a Hexa-core (23.23 GHz Avalanche + 41.82 GHz Blizzard) CPU.",
  },
  {
    id: 7,
    title: "Apple iPhone 13 Pro Max Full Specifications",
    img: "https://www.mobiledokan.com/wp-content/uploads/2021/10/Apple-iPhone-13-Pro-Max-image.jpg",
    Display: "	6.7 inches 1284 x 2778 pixels (458 ppi)",
    Camera: "Back: 12+12 & Front: 12+SL 3D",
    OS: "iOS 15",
    RAM: "6 GB",
    ROM: "512 GB",
    Battery: "Lithium-ion 4352 mAh (non-removable)",
    price: "৳176,999 ",
    description:
      "Apple iPhone 13 Pro Max comes with a 6.7 inches Super Retina XDR OLED Full HD+ screen. It has a Apple iPhone notch design. The back camera is of quad 12+12+12 Megapixel + TOF 3D LiDAR scanner with powerful image processing capability and 4K video recording. The front one is of Dual 12 MP and SL 3D camera. Apple iPhone 13 Pro Max comes with 4352 mAh battery with 27W fast charging solution. It has 6 GB RAM, up to 3.22 GHz Hexa-core CPU and Apple GPU. It is powered by a 5 nm Apple A15 Bionic chipset. The device comes with 128, 256, 512 GB or 1 TB internal storage.",
  },
  {
    id: 8,
    title: "Apple iPhone 13 price in Bangladesh",
    img: "https://www.bdprice.com.bd/wp-content/uploads/2020/11/Apple-iPhone-13-Blue-Price-in-Bangladesh.jpg",
    Display: "6.1″ Super Retina XDR OLED (1170x2532 px)",
    Camera: "Back: 12+12 & Front: 12+SL 3D",
    OS: "iOS 15",
    RAM: "4 GB",
    ROM: "512 GB",
    Battery: "Li-Ion 3240 mAh",
    price: "৳118000",
    description:
      "2x optical zoom out, Digital zoom up to 5x, Portrait mode with advanced bokeh and Depth Control, Portrait Lighting with six effects (Natural, Studio, Contour, Stage, Stage Mono, HighKey Mono), Sensorshift optical image stabilization (Wide), Sevenelement lens (Wide), fiveelement lens (Ultra Wide), True Tone flash with Slow Sync, Panorama (up to 63MP), Sapphire crystal lens cover, 100% Focus Pixels (Wide), Night mode, Deep Fusion, Smart HDR 4, Photographic Styles, Wide color capture for photos and Live Photos, Lens correction (Ultra Wide), Advanced redeye correction, Auto image stabilization, Burst mode, Photo geotagging, Image formats captured: HEIF and JPEG, Audio zoom, True Tone flash, QuickTake video, Timelapse video with stabilization, Night mode Time-lapse, Stereo recording, Playback zoom",
  },
  {
    id: 9,
    title: "Apple iPhone 14 Pro Max price in Bangladesh",
    img: "https://dnc8pt3q0ulny.cloudfront.net/rp/media/14pmp1.jpg",
    Display: "6.7″ LTPO Super Retina XDR OLED (1290x2796 px)",
    Camera: "Back: 48+12+12+TOF 3D & Front: 12+SL 3D",
    OS: "iOS 16",
    RAM: "6 GB",
    ROM: "1TB",
    Battery: "Li-Ion 4323 mAh",
    price: "৳201,599.00",
    description:
      "With this intention, All of our product data collection sources are on the Internet. Our team shared all kinds of reviews, details, and prices in Bangladesh that have been collected from various websites on the Internet. We have tried to present the information to you through verification and selection from the internet. We sincerely apologize for any inconvenience this may cause. Before buying any product, you should check and choose well.",
  },
  {
    id: 10,
    title: "Apple iPhone 14",
    img: "https://www.mobiledokan.co/wp-content/uploads/2021/09/Apple-iPhone-14-Midnight.jpg",
    OS: "iOS 16",
    Display: "6.1 1170x2532 pixels",
    Camera: "12MP 2160p",
    RAM: "6GB ",
    ROM: "512 GB",
    Battery: "3279mAh Li-Ion",
    price: "৳146,999.00",
    description:
      "Apple iPhone 14 will be launched in September 2022. The iPhone 14 launched with the model numbers A2882, A2649, A2881, A2884, A2883, and iPhone 15,5. Firstly, Its dimensional measure is 146.7 x 71.5 x 7.7 mm and the weight is 172 grams. Secondly, the display of the iPhone 14 is a 6.1-inch Super Retina XDR OLED panel with 1170 x 2532 pixels resolution. The display is protected from Scratch-resistant ceramic glass and oleophobic coating. Thirdly and most importantly, It is powered by Apple A16 Bionic and running with iOS 15. Moreover, it has a Hexa-core (23.23 GHz Avalanche + 41.82 GHz Blizzard) CPU.",
  },
  {
    id: 11,
    title: "Apple iPhone 13 Pro Max Full Specifications",
    img: "https://www.mobiledokan.com/wp-content/uploads/2021/10/Apple-iPhone-13-Pro-Max-image.jpg",
    Display: "	6.7 inches 1284 x 2778 pixels (458 ppi)",
    Camera: "Back: 12+12 & Front: 12+SL 3D",
    OS: "iOS 15",
    RAM: "6 GB",
    ROM: "512 GB",
    Battery: "Lithium-ion 4352 mAh (non-removable)",
    price: "৳176,999 ",
    description:
      "Apple iPhone 13 Pro Max comes with a 6.7 inches Super Retina XDR OLED Full HD+ screen. It has a Apple iPhone notch design. The back camera is of quad 12+12+12 Megapixel + TOF 3D LiDAR scanner with powerful image processing capability and 4K video recording. The front one is of Dual 12 MP and SL 3D camera. Apple iPhone 13 Pro Max comes with 4352 mAh battery with 27W fast charging solution. It has 6 GB RAM, up to 3.22 GHz Hexa-core CPU and Apple GPU. It is powered by a 5 nm Apple A15 Bionic chipset. The device comes with 128, 256, 512 GB or 1 TB internal storage.",
  },
  {
    id: 12,
    title: "Apple iPhone 13 price in Bangladesh",
    img: "https://www.bdprice.com.bd/wp-content/uploads/2020/11/Apple-iPhone-13-Blue-Price-in-Bangladesh.jpg",
    Display: "6.1″ Super Retina XDR OLED (1170x2532 px)",
    Camera: "Back: 12+12 & Front: 12+SL 3D",
    OS: "iOS 15",
    RAM: "4 GB",
    ROM: "512 GB",
    Battery: "Li-Ion 3240 mAh",
    price: "৳118000",
    description:
      "2x optical zoom out, Digital zoom up to 5x, Portrait mode with advanced bokeh and Depth Control, Portrait Lighting with six effects (Natural, Studio, Contour, Stage, Stage Mono, HighKey Mono), Sensorshift optical image stabilization (Wide), Sevenelement lens (Wide), fiveelement lens (Ultra Wide), True Tone flash with Slow Sync, Panorama (up to 63MP), Sapphire crystal lens cover, 100% Focus Pixels (Wide), Night mode, Deep Fusion, Smart HDR 4, Photographic Styles, Wide color capture for photos and Live Photos, Lens correction (Ultra Wide), Advanced redeye correction, Auto image stabilization, Burst mode, Photo geotagging, Image formats captured: HEIF and JPEG, Audio zoom, True Tone flash, QuickTake video, Timelapse video with stabilization, Night mode Time-lapse, Stereo recording, Playback zoom",
  },
];
export const getSignData = (id) => {
  const data = demoData.find((item) => item.id === id);

  return data;
};
